apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer   
  namespace: cert-manager                                                                        
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: "xxx@example.com"                                       
    privateKeySecretRef:
      name: letsencrypt                                   
    solvers:
    - dns01:
        route53:
          accessKeyID: xxxxx
          hostedZoneID: xxxxx                        
          region: us-east-1                                   
          secretAccessKeySecretRef:
            name: "aws-secret"                                     
            key: "awsSecretAccessKey"                  
