apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer   
  namespace: cert-manager                                                                        
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    email: "xxx@email.com"                                       
    privateKeySecretRef:
      name: letsencrypt                                   
    solvers:
    - dns01:
        route53:
          accessKeyID: xxxxxx                               
          hostedZoneID: xxxxxx                          
          region: us-east-1                                   
          secretAccessKeySecretRef:
            name: "aws-secret"                                     
            key: "awsSecretAccessKey"   
    - http01:
        ingress:
          class: openshift-default                         
